repos:
  # SwiftLint for Swift code formatting and linting
  - repo: https://github.com/realm/SwiftLint
    rev: 0.59.1
    hooks:
      - id: swiftlint
        args: [--fix]
        files: \.(swift)$
        types: [file]
        additional_dependencies: []

  # General pre-commit hooks for all file types
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: debug-statements

  # YAML formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [yaml, json]
        additional_dependencies:
          - prettier@3.1.0

# Global settings
fail_fast: false
default_language_version:
  python: python3
