# SwiftLint Configuration File

# Disable rules that are too strict for this project
disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - type_body_length
  - file_length
  - identifier_name
  - type_name

# Enable rules that are important for code quality
opt_in_rules:
  - empty_count
  - force_unwrapping
  - implicitly_unwrapped_optional
  - overridden_super_call
  - redundant_nil_coalescing
  - unused_import
  - vertical_whitespace

# Configure specific rules
line_length:
  warning: 120
  error: 150

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

# Exclude certain files/directories
excluded:
  - Pods
  - Carthage
  - build
  - DerivedData
  - fluencyTests
  - fluencyUITests

# Custom rules can be added here
custom_rules:
  # Example custom rule (uncomment if needed)
  # no_print:
  #   name: "No Print"
  #   regex: 'print\('
  #   message: "Use proper logging instead of print statements"
  #   severity: warning
