name: Quick Build & Test

on:
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.2"

      - name: Cache derived data
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: derived-data-${{ hashFiles('fluency.xcodeproj/project.pbxproj') }}
          restore-keys: |
            derived-data-

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install pre-commit
        run: |
          pip install pre-commit

      - name: Install pre-commit hooks
        run: |
          pre-commit install-hooks

      - name: Run pre-commit on changed files
        run: |
          # Run pre-commit on all files to ensure consistency
          pre-commit run --all-files

      - name: Build and Test
        run: |
          xcodebuild clean test \
            -project fluency.xcodeproj \
            -scheme fluency \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
            -derivedDataPath ~/Library/Developer/Xcode/DerivedData \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            | xcpretty

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: ~/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult
          retention-days: 7
